<?php

return [
    "transactionLogItemTypeId" => [
        "1"  => "autoAddDrop",
        "2"  => "manualAddDrop",
        "4"  => "trade",
        "11" => "tradeAccepted",
        "13" => "tradeVetoed",
    ],
    "activityType"             => [
        "0" => "LM Action",
        "1" => "LM Note",
        "2" => "Transaction",
        "3" => "Message",
        "4" => "Trophy",
    ],
    "moveTypeId"               => [
        "1" => "moved",
        "2" => "added",
        "3" => "dropped",
        "4" => "traded",
        "5" => "drafted",
    ],
    "proTeamMoveType"          => [
        "1" => "signed",
        "2" => "dropped",
        "3" => "traded",
    ],
    "analysisMetrics"          => [
        "numQuarterbacks"                        => ["sort" => 0, "name" => "Number of QBs", "format" => false],
        "totalCost"                              => ["sort" => 0, "name" => "Total contract cost", "format" => true],
        "totalGuaranteed"                        => ["sort" => 0, "name" => "Total guaranteed money", "format" => true],
        "averageAdp"                             => ["sort" => 1, "name" => "Average draft position`", "format" => false],
        "averagePercentOwned"                    => ["sort" => 0, "name" => "Average percent owned by other ESPN teams", "format" => false],
        "numPlayersTopOfPositionRank"            => ["sort" => 0, "name" => "Number of drafted players who rank #1 for their position", "format" => false],
        "playersTopOfPositionRank"               => ["sort" => 0, "name" => "Players drafted who rank #1 for their position", "format" => false],
        "totalPointsLastSeason"                  => ["sort" => 0, "name" => "Total points in 2014 for all drafted players", "format" => false],
        "averageWeeklyPointsLastSeasonPerPlayer" => ["sort" => 0, "name" => "Average weekly points in 2014 per player", "format" => false],
        "averageTotalPointsLastSeasonPerPlayer"  => ["sort" => 0, "name" => "Average total points in 2014 per player", "format" => false],
        // "totalCostFormatted" => ["sort" => 0, "name" => "", "format" => false],
        // "totalGuaranteedFormatted" => ["sort" => 0, "name" => "", "format" => false],
    ],
    "regularUpdates"           => [
        "439427",
        "111799",
        "200405",
    ],
    "phrases"                  => [
        "neutral"      => ["Heads up!", "Just FYI.", "FYI.", "Just so you know!", "No big deal, but just FYI.", "Meh."],
        "positive"     => ["Eureka!", "Hallelujah!", "Score!", "Heck yeah!", "Good news!", "Rock on!", "Yesss!", "Sweet!", "Cool!"],
        "negative"     => ["Nuts.", "Aww rats.", "Darnit!", "Shoot!", "Oh no!", "Gadzooks!", "Shucks!", "Bad news :(", "Fiddle sticks!", "Nooo!", "Awww dicks!", "Blast!", "Jumpin' Jehosaphat!"],
        "veryNegative" => ["Fuck.", "Well shit.", "FUCK.", "Mother fucker."],
        "matchupEnd"   => ["It's done!", "That's the game.", "It's all over.", "All done!", "That's it!", "Pencils down!", "And the clock hits zero!"],
    ],
    "slack"                    => [
        "111799" => [
            "channelId" => "G1LKZN988",
        ],
        "200405" => [
            "channelId" => "G6H1RAWQJ",
        ],
        "439427" => [
            "channelId" => "G6HPHCCKW",
        ],
    ],
    "leagues"                  => [
        "ids"    => ["111799", "200405", "439427"],
        "200405" => "Destiny Fantasy Football",
        "111799" => "RedditTryHard",
        "439427" => "TryHard Fantasy Football",
    ],
    'pprLeagues'               => [
        '439427',
    ],
    "healthStatus"             => [
        "5"  => "on IR",
        "4"  => "out",
        "11" => "inactive",
        "13" => "suspended",
        "3"  => "doubtful",
        "2"  => "questionable",
        "1"  => "probable",
        "0"  => "active",
    ],
    "rosterStatus"             => [
        "0" => "FA",
        "1" => "owned",
        "2" => "waivers",
    ],
    "defaultPositionId"        => [
        "1"  => "QB",
        "2"  => "RB",
        "3"  => "WR",
        "4"  => "TE",
        "5"  => "K",
        "16" => "D/ST",
    ],
    "eligibleSlotCategoryIds"  => [

    ],
    "nflScheduleWeeks"         => [
        "2018-09-04 13:00:00+0000" => ["seasontype" => "2", "week" => "1", "type" => "regular"],
        "2018-09-11 13:00:00+0000" => ["seasontype" => "2", "week" => "2", "type" => "regular"],
        "2018-09-18 13:00:00+0000" => ["seasontype" => "2", "week" => "3", "type" => "regular"],
        "2018-09-25 13:00:00+0000" => ["seasontype" => "2", "week" => "4", "type" => "regular"],
        "2018-10-02 13:00:00+0000" => ["seasontype" => "2", "week" => "5", "type" => "regular"],
        "2018-10-09 13:00:00+0000" => ["seasontype" => "2", "week" => "6", "type" => "regular"],
        "2018-10-16 13:00:00+0000" => ["seasontype" => "2", "week" => "7", "type" => "regular"],
        "2018-10-23 13:00:00+0000" => ["seasontype" => "2", "week" => "8", "type" => "regular"],
        "2018-10-30 13:00:00+0000" => ["seasontype" => "2", "week" => "9", "type" => "regular"],
        "2018-11-06 13:00:00+0000" => ["seasontype" => "2", "week" => "10", "type" => "regular"],
        "2018-11-13 13:00:00+0000" => ["seasontype" => "2", "week" => "11", "type" => "regular"],
        "2018-11-20 13:00:00+0000" => ["seasontype" => "2", "week" => "12", "type" => "regular"],
        "2018-11-27 13:00:00+0000" => ["seasontype" => "2", "week" => "13", "type" => "regular"],
        "2018-12-04 13:00:00+0000" => ["seasontype" => "2", "week" => "14", "type" => "regular"],
        "2018-12-11 13:00:00+0000" => ["seasontype" => "2", "week" => "15", "type" => "regular"],
        "2018-12-18 13:00:00+0000" => ["seasontype" => "2", "week" => "16", "type" => "regular"],
        "2018-12-25 13:00:00+0000" => ["seasontype" => "2", "week" => "17", "type" => "regular"],
        "2019-01-01 13:00:00+0000" => ["seasontype" => "3", "week" => "1", "type" => "wild card"],
        "2019-01-08 13:00:00+0000" => ["seasontype" => "3", "week" => "2", "type" => "division"],
        "2019-01-15 13:00:00+0000" => ["seasontype" => "3", "week" => "3", "type" => "conference"],
        "2019-01-22 13:00:00+0000" => ["seasontype" => "3", "week" => "4", "type" => "pro bowl"],
        "2019-01-29 13:00:00+0000" => ["seasontype" => "3", "week" => "5", "type" => "super bowl"],
    ],
    "proTeamIds"               => [
        "26" => "Seahawks",
        "2"  => "Bills",
        "34" => "Texans",
        "14" => "Rams",
        "7"  => "Broncos",
        "20" => "Jets",
        "15" => "Dolphins",
        "33" => "Ravens",
        "22" => "Cardinals",
        "17" => "Patriots",
        "8"  => "Lions",
        "21" => "Eagles",
        "9"  => "Packers",
        "29" => "Panthers",
        "16" => "Vikings",
        "12" => "Chiefs",
        "6"  => "Cowboys",
        "4"  => "Bengals",
        "25" => "49ers",
        "5"  => "Browns",
        "11" => "Colts",
        "23" => "Steelers",
        "27" => "Buccaneers",
        "19" => "Giants",
        "3"  => "Bears",
        "1"  => "Falcons",
        "13" => "Raiders",
        "18" => "Saints",
        "24" => "Chargers",
        "28" => "Redskins",
        "10" => "Titans",
        "30" => "Jaguars",
    ],
    "proTeamNames"             => [
        "Patriots"             => 17,
        "Steelers"             => 23,
        "Bears"                => 3,
        "Packers"              => 9,
        "Texans"               => 34,
        "Chiefs"               => 12,
        "Jets"                 => 20,
        "Browns"               => 5,
        "Bills"                => 2,
        "Colts"                => 11,
        "Redskins"             => 28,
        "Dolphins"             => 15,
        "Jaguars"              => 30,
        "Panthers"             => 29,
        "Rams"                 => 14,
        "Seahawks"             => 26,
        "Cardinals"            => 22,
        "Saints"               => 18,
        "Chargers"             => 24,
        "Lions"                => 8,
        "Buccaneers"           => 27,
        "Titans"               => 10,
        "Raiders"              => 13,
        "Bengals"              => 4,
        "Broncos"              => 7,
        "Ravens"               => 33,
        "Cowboys"              => 6,
        "Giants"               => 19,
        "Falcons"              => 1,
        "Eagles"               => 21,
        "49ers"                => 25,
        "Vikings"              => 16,
        "NE"                   => 17,
        "PIT"                  => 23,
        "CHI"                  => 3,
        "GB"                   => 9,
        "HOU"                  => 34,
        "KC"                   => 12,
        "NYJ"                  => 20,
        "CLE"                  => 5,
        "BUF"                  => 2,
        "IND"                  => 11,
        "WSH"                  => 28,
        "MIA"                  => 15,
        "JAX"                  => 30,
        "CAR"                  => 29,
        "LAR"                  => 14,
        "SEA"                  => 26,
        "ARI"                  => 22,
        "NO"                   => 18,
        "LAC"                  => 24,
        "DET"                  => 8,
        "TB"                   => 27,
        "TEN"                  => 10,
        "OAK"                  => 13,
        "CIN"                  => 4,
        "DEN"                  => 7,
        "BAL"                  => 33,
        "DAL"                  => 6,
        "NYG"                  => 19,
        "ATL"                  => 1,
        "PHI"                  => 21,
        "SF"                   => 25,
        "MIN"                  => 16,
        "New England Patriots" => 17,
        "Pittsburgh Steelers"  => 23,
        "Chicago Bears"        => 3,
        "Green Bay Packers"    => 9,
        "Houston Texans"       => 34,
        "Kansas City Chiefs"   => 12,
        "New York Jets"        => 20,
        "Cleveland Browns"     => 5,
        "Buffalo Bills"        => 2,
        "Indianapolis Colts"   => 11,
        "Washington Redskins"  => 28,
        "Miami Dolphins"       => 15,
        "Jacksonville Jaguars" => 30,
        "Carolina Panthers"    => 29,
        "LA Rams"              => 14,
        "Los Angeles Rams"     => 14,
        "Seattle Seahawks"     => 26,
        "Arizona Cardinals"    => 22,
        "New Orleans Saints"   => 18,
        "Los Angeles Chargers" => 24,
        "LA Chargers"          => 24,
        "Detroit Lions"        => 8,
        "Tampa Bay Buccaneers" => 27,
        "Tennessee Titans"     => 10,
        "Oakland Raiders"      => 13,
        "Cincinnati Bengals"   => 4,
        "Denver Broncos"       => 7,
        "Baltimore Ravens"     => 33,
        "Dallas Cowboys"       => 6,
        "New York Giants"      => 19,
        "Atlanta Falcons"      => 1,
        "Philadelphia Eagles"  => 21,
        "San Francisco 49ers"  => 25,
        "Minnesota Vikings"    => 16,
    ],
    "scoringItems"             => [
        "0"   => [
            "isReverseItem"     => false,
            "points"            => 11,
            "isTeamScoringItem" => false,
            "playerCategory"    => "passing",
            "scoringName"       => "Each Pass Attempted (PA)",
            "scoringNameAbbr"   => "PA",
        ],
        "1"   => [
            "isReverseItem"     => false,
            "points"            => 2,
            "isTeamScoringItem" => false,
            "playerCategory"    => "passing",
            "scoringName"       => "Each Pass Completed (PC)",
            "scoringNameAbbr"   => "PC",
        ],
        "2"   => [
            "isReverseItem"     => false,
            "points"            => 3,
            "isTeamScoringItem" => false,
            "playerCategory"    => "passing",
            "scoringName"       => "Each Incomplete Pass (INC)",
            "scoringNameAbbr"   => "INC",
        ],
        "3"   => [
            "scoringName"     => "Passing Yards",
            "scoringNameAbbr" => "YDS",
        ],
        "4"   => [
            "isReverseItem"     => false,
            "points"            => 4,
            "isTeamScoringItem" => false,
            "playerCategory"    => "passing",
            "scoringName"       => "TD Pass (PTD)",
            "scoringNameAbbr"   => "PTD",
        ],
        "8"   => [
            "isReverseItem"     => false,
            "points"            => 1,
            "isTeamScoringItem" => false,
            "playerCategory"    => "passing",
            "scoringName"       => "Every 25 passing yards  (PY25)",
            "scoringNameAbbr"   => "PY25",
        ],
        "15"  => [
            "isReverseItem"     => false,
            "points"            => 5,
            "isTeamScoringItem" => false,
            "playerCategory"    => "passing",
            "scoringName"       => "40+ yard TD pass bonus (PTD40)",
            "scoringNameAbbr"   => "PTD40",
        ],
        "16"  => [
            "isReverseItem"     => false,
            "points"            => 6,
            "isTeamScoringItem" => false,
            "playerCategory"    => "passing",
            "scoringName"       => "50+ yard TD pass bonus (PTD50)",
            "scoringNameAbbr"   => "PTD50",
        ],
        "17"  => [
            "isReverseItem"     => false,
            "points"            => 9,
            "isTeamScoringItem" => false,
            "playerCategory"    => "passing",
            "scoringName"       => "300-399 yard passing game (P300)",
            "scoringNameAbbr"   => "P300",
        ],
        "18"  => [
            "isReverseItem"     => false,
            "points"            => 10,
            "isTeamScoringItem" => false,
            "playerCategory"    => "passing",
            "scoringName"       => "400+ yard passing game (P400)",
            "scoringNameAbbr"   => "P400",
        ],
        "19"  => [
            "isReverseItem"     => false,
            "points"            => 8,
            "isTeamScoringItem" => false,
            "playerCategory"    => "passing",
            "scoringName"       => "2pt Passing Conversion (2PC)",
            "scoringNameAbbr"   => "2PC",
        ],
        "20"  => [
            "isReverseItem"     => false,
            "points"            => 7,
            "isTeamScoringItem" => false,
            "playerCategory"    => "passing",
            "scoringName"       => "Interceptions Thrown (INT)",
            "scoringNameAbbr"   => "INT",
        ],
        "23"  => [
            "isReverseItem"     => false,
            "points"            => 14,
            "isTeamScoringItem" => false,
            "playerCategory"    => "rushing",
            "scoringName"       => "Rushing Attempts (RA)",
            "scoringNameAbbr"   => "RA",
        ],
        "24"  => [
            "scoringName"     => "Rushing Yards",
            "scoringNameAbbr" => "RSHYDS",
        ],
        "25"  => [
            "isReverseItem"     => false,
            "points"            => 15,
            "isTeamScoringItem" => false,
            "playerCategory"    => "rushing",
            "scoringName"       => "TD Rush (RTD)",
            "scoringNameAbbr"   => "RTD",
        ],
        "26"  => [
            "isReverseItem"     => false,
            "points"            => 18,
            "isTeamScoringItem" => false,
            "playerCategory"    => "rushing",
            "scoringName"       => "2pt Rushing Conversion (2PR)",
            "scoringNameAbbr"   => "2PR",
        ],
        "28"  => [
            "isReverseItem"     => false,
            "points"            => 13,
            "isTeamScoringItem" => false,
            "playerCategory"    => "rushing",
            "scoringName"       => "Every 10 rushing yards (RY10)",
            "scoringNameAbbr"   => "RY10",
        ],
        "35"  => [
            "isReverseItem"     => false,
            "points"            => 16,
            "isTeamScoringItem" => false,
            "playerCategory"    => "rushing",
            "scoringName"       => "40+ yard TD rush bonus (RTD40)",
            "scoringNameAbbr"   => "RTD40",
        ],
        "36"  => [
            "isReverseItem"     => false,
            "points"            => 17,
            "isTeamScoringItem" => false,
            "playerCategory"    => "rushing",
            "scoringName"       => "50+ yard TD rush bonus (RTD50)",
            "scoringNameAbbr"   => "RTD50",
        ],
        "37"  => [
            "isReverseItem"     => false,
            "points"            => 19,
            "isTeamScoringItem" => false,
            "playerCategory"    => "rushing",
            "scoringName"       => "100-199 yard rushing game (RY100)",
            "scoringNameAbbr"   => "RY100",
        ],
        "38"  => [
            "isReverseItem"     => false,
            "points"            => 20,
            "isTeamScoringItem" => false,
            "playerCategory"    => "rushing",
            "scoringName"       => "200+ yard rushing game (RY200)",
            "scoringNameAbbr"   => "RY200",
        ],
        "42"  => [
            "scoringName"     => "Receiving Yards",
            "scoringNameAbbr" => "RECYDS",
        ],
        "43"  => [
            "isReverseItem"     => false,
            "points"            => 23,
            "isTeamScoringItem" => false,
            "playerCategory"    => "receiving",
            "scoringName"       => "TD Reception (RETD)",
            "scoringNameAbbr"   => "RETD",
        ],
        "44"  => [
            "isReverseItem"     => false,
            "points"            => 26,
            "isTeamScoringItem" => false,
            "playerCategory"    => "receiving",
            "scoringName"       => "2pt Receiving Conversion (2PRE)",
            "scoringNameAbbr"   => "2PRE",
        ],
        "45"  => [
            "isReverseItem"     => false,
            "points"            => 24,
            "isTeamScoringItem" => false,
            "playerCategory"    => "receiving",
            "scoringName"       => "40+ yard TD rec bonus (RETD40)",
            "scoringNameAbbr"   => "RETD40",
        ],
        "46"  => [
            "isReverseItem"     => false,
            "points"            => 25,
            "isTeamScoringItem" => false,
            "playerCategory"    => "receiving",
            "scoringName"       => "50+ yard TD rec bonus (RETD50)",
            "scoringNameAbbr"   => "RETD50",
        ],
        "48"  => [
            "isReverseItem"     => false,
            "points"            => 21,
            "isTeamScoringItem" => false,
            "playerCategory"    => "receiving",
            "scoringName"       => "Every 10 receiving yards (REY10)",
            "scoringNameAbbr"   => "REY10",
        ],
        "53"  => [
            "isReverseItem"     => false,
            "points"            => 22,
            "isTeamScoringItem" => false,
            "playerCategory"    => "receiving",
            "scoringName"       => "Each reception (REC)",
            "scoringNameAbbr"   => "REC",
        ],
        "56"  => [
            "isReverseItem"     => false,
            "points"            => 27,
            "isTeamScoringItem" => false,
            "playerCategory"    => "receiving",
            "scoringName"       => "100-199 yard receiving game (REY100)",
            "scoringNameAbbr"   => "REY100",
        ],
        "57"  => [
            "isReverseItem"     => false,
            "points"            => 28,
            "isTeamScoringItem" => false,
            "playerCategory"    => "receiving",
            "scoringName"       => "200+ yard receiving game (REY200)",
            "scoringNameAbbr"   => "REY200",
        ],
        "58"  => [
            "isReverseItem"     => false,
            "points"            => 29,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "scoringName"       => "Receiving Target (RET)",
            "scoringNameAbbr"   => "RET",
        ],
        "63"  => [
            "isReverseItem"     => false,
            "points"            => 34,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "scoringName"       => "Fumble Recovered for TD (FTD)",
            "scoringNameAbbr"   => "FTD",
        ],
        "64"  => [
            "isReverseItem"     => false,
            "points"            => 12,
            "isTeamScoringItem" => false,
            "playerCategory"    => "passing",
            "scoringName"       => "Sacked (SK)",
            "scoringNameAbbr"   => "SK",
        ],
        "68"  => [
            "isReverseItem"     => false,
            "points"            => 35,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "scoringName"       => "Total Fumbles (FUM)",
            "scoringNameAbbr"   => "FUM",
        ],
        "72"  => [
            "isReverseItem"     => false,
            "points"            => 36,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "scoringName"       => "Total Fumbles Lost (FUML)",
            "scoringNameAbbr"   => "FUML",
        ],
        "74"  => [
            "isReverseItem"     => false,
            "points"            => 52,
            "isTeamScoringItem" => false,
            "playerCategory"    => "kicking",
            "scoringName"       => "FG Made (50+ yards) (FG50)",
            "scoringNameAbbr"   => "FG50",
        ],
        "75"  => [
            "isReverseItem"     => false,
            "points"            => 55,
            "isTeamScoringItem" => false,
            "playerCategory"    => "kicking",
            "scoringName"       => "FG  Attempted (50+ yards) (FGA50)",
            "scoringNameAbbr"   => "FGA50",
        ],
        "76"  => [
            "isReverseItem"     => false,
            "points"            => 58,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "FG Missed (50+ yards) (FGM50)",
            "scoringNameAbbr"   => "FGM50",
        ],
        "77"  => [
            "isReverseItem"     => false,
            "points"            => 51,
            "isTeamScoringItem" => false,
            "playerCategory"    => "kicking",
            "scoringName"       => "FG Made (40-49 yards) (FG40)",
            "scoringNameAbbr"   => "FG40",
        ],
        "78"  => [
            "isReverseItem"     => false,
            "points"            => 54,
            "isTeamScoringItem" => false,
            "playerCategory"    => "kicking",
            "scoringName"       => "FG Attempted (40-49 yards) (FGA40)",
            "scoringNameAbbr"   => "FGA40",
        ],
        "79"  => [
            "isReverseItem"     => false,
            "points"            => 57,
            "isTeamScoringItem" => false,
            "playerCategory"    => "kicking",
            "scoringName"       => "FG Missed (40-49 yards) (FGM40)",
            "scoringNameAbbr"   => "FGM40",
        ],
        "80"  => [
            "isReverseItem"     => false,
            "points"            => 50,
            "isTeamScoringItem" => false,
            "playerCategory"    => "kicking",
            "scoringName"       => "FG Made (0-39 yards) (FG0)",
            "scoringNameAbbr"   => "FG0",
        ],
        "81"  => [
            "isReverseItem"     => false,
            "points"            => 53,
            "isTeamScoringItem" => false,
            "playerCategory"    => "kicking",
            "scoringName"       => "FG Attempted (0-39 yards) (FGA9)",
            "scoringNameAbbr"   => "FGA9",
        ],
        "82"  => [
            "isReverseItem"     => false,
            "points"            => 56,
            "isTeamScoringItem" => false,
            "playerCategory"    => "kicking",
            "scoringName"       => "FG Missed (0-39 yards) (FGM0)",
            "scoringNameAbbr"   => "FGM0",
        ],
        "83"  => [
            "isReverseItem"     => false,
            "points"            => 47,
            "isTeamScoringItem" => false,
            "playerCategory"    => "kicking",
            "scoringName"       => "Total FG Made (FG)",
            "scoringNameAbbr"   => "FG",
        ],
        "84"  => [
            "isReverseItem"     => false,
            "points"            => 48,
            "isTeamScoringItem" => false,
            "playerCategory"    => "kicking",
            "scoringName"       => "Total FG Attempted (FGA)",
            "scoringNameAbbr"   => "FGA",
        ],
        "85"  => [
            "isReverseItem"     => false,
            "points"            => 49,
            "isTeamScoringItem" => false,
            "playerCategory"    => "kicking",
            "scoringName"       => "Total FG Missed (FGM)",
            "scoringNameAbbr"   => "FGM",
        ],
        "86"  => [
            "isReverseItem"     => false,
            "points"            => 44,
            "isTeamScoringItem" => false,
            "playerCategory"    => "kicking",
            "scoringName"       => "Each PAT Made (PAT)",
            "scoringNameAbbr"   => "PAT",
        ],
        "87"  => [
            "isReverseItem"     => false,
            "points"            => 45,
            "isTeamScoringItem" => false,
            "playerCategory"    => "kicking",
            "scoringName"       => "Each PAT Attempted (PATA)",
            "scoringNameAbbr"   => "PATA",
        ],
        "88"  => [
            "isReverseItem"     => false,
            "points"            => 46,
            "isTeamScoringItem" => false,
            "playerCategory"    => "kicking",
            "scoringName"       => "Each PAT Missed (PATM)",
            "scoringNameAbbr"   => "PATM",
        ],
        "89"  => [
            "isReverseItem"     => false,
            "points"            => 119,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "prettyKey"         => "Points Allowed",
            "prettyValue"       => "0",
            "scoringName"       => "0 points allowed (PA0)",
            "scoringNameAbbr"   => "PA0",
        ],
        "90"  => [
            "isReverseItem"     => false,
            "points"            => 120,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "prettyKey"         => "Points Allowed",
            "prettyValue"       => "1-6",
            "scoringName"       => "1-6 points allowed (PA1)",
            "scoringNameAbbr"   => "PA1",
        ],
        "91"  => [
            "isReverseItem"     => false,
            "points"            => 121,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "prettyKey"         => "Points Allowed",
            "prettyValue"       => "7-13",
            "scoringName"       => "7-13 points allowed (PA7)",
            "scoringNameAbbr"   => "PA7",
        ],
        "92"  => [
            "isReverseItem"     => false,
            "points"            => 122,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "prettyKey"         => "Points Allowed",
            "prettyValue"       => "14-17",
            "scoringName"       => "14-17 points allowed (PA14)",
            "scoringNameAbbr"   => "PA14",
        ],
        "93"  => [
            "isReverseItem"     => false,
            "points"            => 41,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "prettyKey"         => "Block kick for TD",
            "scoringName"       => "Blocked Punt or FG return for TD (BLKKRTD)",
            "scoringNameAbbr"   => "BLKKRTD",
        ],
        "93"  => [
            "isReverseItem"     => false,
            "points"            => 110,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "prettyKey"         => "Block kick for TD",
            "scoringName"       => "Blocked Punt or FG return for TD (BLKKRTD)",
            "scoringNameAbbr"   => "BLKKRTD",
        ],
        "95"  => [
            "isReverseItem"     => false,
            "points"            => 78,
            "isTeamScoringItem" => false,
            "playerCategory"    => "defense",
            "scoringName"       => "Each Interception (INT)",
            "scoringNameAbbr"   => "INT",
        ],
        "95"  => [
            "isReverseItem"     => false,
            "points"            => 112,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "Each Interception (INT)",
            "scoringNameAbbr"   => "INT",
        ],
        "96"  => [
            "isReverseItem"     => false,
            "points"            => 79,
            "isTeamScoringItem" => false,
            "playerCategory"    => "defense",
            "scoringName"       => "Each Fumble Recovered (FR)",
            "scoringNameAbbr"   => "FR",
        ],
        "96"  => [
            "isReverseItem"     => false,
            "points"            => 113,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "Each Fumble Recovered (FR)",
            "scoringNameAbbr"   => "FR",
        ],
        "97"  => [
            "isReverseItem"     => false,
            "points"            => 77,
            "isTeamScoringItem" => false,
            "playerCategory"    => "defense",
            "prettyKey"         => "Block kick",
            "scoringName"       => "Blocked Punt, PAT or FG (BLKK)",
            "scoringNameAbbr"   => "BLKK",
        ],
        "97"  => [
            "isReverseItem"     => false,
            "points"            => 111,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "prettyKey"         => "Block kick",
            "scoringName"       => "Blocked Punt, PAT or FG (BLKK)",
            "scoringNameAbbr"   => "BLKK",
        ],
        "98"  => [
            "isReverseItem"     => false,
            "points"            => 81,
            "isTeamScoringItem" => false,
            "playerCategory"    => "defense",
            "prettyKey"         => "Safety",
            "scoringName"       => "Each Safety (SF)",
            "scoringNameAbbr"   => "SF",
        ],
        "98"  => [
            "isReverseItem"     => false,
            "points"            => 115,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "prettyKey"         => "Safety",
            "scoringName"       => "Each Safety (SF)",
            "scoringNameAbbr"   => "SF",
        ],
        "99"  => [
            "isReverseItem"     => false,
            "points"            => 75,
            "isTeamScoringItem" => false,
            "playerCategory"    => "defense",
            "prettyKey"         => "Sacks",
            "scoringName"       => "Each Sack (SK)",
            "scoringNameAbbr"   => "SK",
        ],
        "99"  => [
            "isReverseItem"     => false,
            "points"            => 104,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "prettyKey"         => "Sacks",
            "scoringName"       => "Each Sack (SK)",
            "scoringNameAbbr"   => "SK",
        ],
        "101" => [
            "isReverseItem"     => false,
            "points"            => 32,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "scoringName"       => "Kickoff Return TD (KRTD)",
            "scoringNameAbbr"   => "KRTD",
        ],
        "101" => [
            "isReverseItem"     => false,
            "points"            => 108,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "Kickoff Return TD (KRTD)",
            "scoringNameAbbr"   => "KRTD",
        ],
        "102" => [
            "isReverseItem"     => false,
            "points"            => 33,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "scoringName"       => "Punt Return TD (PRTD)",
            "scoringNameAbbr"   => "PRTD",
        ],
        "102" => [
            "isReverseItem"     => false,
            "points"            => 109,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "Punt Return TD (PRTD)",
            "scoringNameAbbr"   => "PRTD",
        ],
        "103" => [
            "isReverseItem"     => false,
            "points"            => 39,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "prettyKey"         => "Pick six",
            "scoringName"       => "Interception Return TD (INTTD)",
            "scoringNameAbbr"   => "INTTD",
        ],
        "103" => [
            "isReverseItem"     => false,
            "points"            => 106,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "prettyKey"         => "Pick six",
            "scoringName"       => "Interception Return TD (INTTD)",
            "scoringNameAbbr"   => "INTTD",
        ],
        "104" => [
            "isReverseItem"     => false,
            "points"            => 40,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "prettyKey"         => "Fumble Return TD",
            "scoringName"       => "Fumble Return TD (FRTD)",
            "scoringNameAbbr"   => "FRTD",
        ],
        "104" => [
            "isReverseItem"     => false,
            "points"            => 107,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "prettyKey"         => "Fumble Return TD",
            "scoringName"       => "Fumble Return TD (FRTD)",
            "scoringNameAbbr"   => "FRTD",
        ],
        "106" => [
            "isReverseItem"     => false,
            "points"            => 80,
            "isTeamScoringItem" => false,
            "playerCategory"    => "defense",
            "scoringName"       => "Each Fumble Forced (FF)",
            "scoringNameAbbr"   => "FF",
        ],
        "106" => [
            "isReverseItem"     => false,
            "points"            => 114,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "Each Fumble Forced (FF)",
            "scoringNameAbbr"   => "FF",
        ],
        "107" => [
            "isReverseItem"     => false,
            "points"            => 82,
            "isTeamScoringItem" => false,
            "playerCategory"    => "defense",
            "scoringName"       => "Assisted Tackles (TKA)",
            "scoringNameAbbr"   => "TKA",
        ],
        "108" => [
            "isReverseItem"     => false,
            "points"            => 83,
            "isTeamScoringItem" => false,
            "playerCategory"    => "defense",
            "scoringName"       => "Solo Tackles (TKS)",
            "scoringNameAbbr"   => "TKS",
        ],
        "109" => [
            "isReverseItem"     => false,
            "points"            => 76,
            "isTeamScoringItem" => false,
            "playerCategory"    => "defense",
            "scoringName"       => "Total Tackles (TK)",
            "scoringNameAbbr"   => "TK",
        ],
        "109" => [
            "isReverseItem"     => false,
            "points"            => 105,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "Total Tackles (TK)",
            "scoringNameAbbr"   => "TK",
        ],
        "112" => [
            "isReverseItem"     => false,
            "points"            => 84,
            "isTeamScoringItem" => false,
            "playerCategory"    => "defense",
            "scoringName"       => "Stuffs (SF)",
            "scoringNameAbbr"   => "SF",
        ],
        "112" => [
            "isReverseItem"     => false,
            "points"            => 116,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "Stuffs (SF)",
            "scoringNameAbbr"   => "SF",
        ],
        "113" => [
            "isReverseItem"     => false,
            "points"            => 85,
            "isTeamScoringItem" => false,
            "playerCategory"    => "coach",
            "scoringName"       => "Passes Defensed (PD)",
            "scoringNameAbbr"   => "PD",
        ],
        "113" => [
            "isReverseItem"     => false,
            "points"            => 117,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "Passes Defensed (PD)",
            "scoringNameAbbr"   => "PD",
        ],
        "114" => [
            "isReverseItem"     => false,
            "points"            => 30,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "scoringName"       => "Kickoff Return Yards (KR)",
            "scoringNameAbbr"   => "KR",
        ],
        "114" => [
            "isReverseItem"     => false,
            "points"            => 102,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "Kickoff Return Yards (KR)",
            "scoringNameAbbr"   => "KR",
        ],
        "115" => [
            "isReverseItem"     => false,
            "points"            => 31,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "scoringName"       => "Punt Return Yards (PR)",
            "scoringNameAbbr"   => "PR",
        ],
        "118" => [
            "isReverseItem"     => false,
            "points"            => 103,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "Every 10 punt return yards (PR10)",
            "scoringNameAbbr"   => "PR10",
        ],
        "120" => [
            "isReverseItem"     => false,
            "points"            => 118,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "prettyKey"         => "Points allowed",
            "scoringName"       => "Points Allowed (PA)",
            "scoringNameAbbr"   => "PA",
        ],
        "121" => [
            "isReverseItem"     => false,
            "points"            => 123,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "18-21 points allowed (PA18)",
            "scoringNameAbbr"   => "PA18",
        ],
        "122" => [
            "isReverseItem"     => false,
            "points"            => 124,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "22-27 points allowed (PA22)",
            "scoringNameAbbr"   => "PA22",
        ],
        "123" => [
            "isReverseItem"     => false,
            "points"            => 125,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "28-34 points allowed (PA28)",
            "scoringNameAbbr"   => "PA28",
        ],
        "124" => [
            "isReverseItem"     => false,
            "points"            => 126,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "35-45 points allowed (PA35)",
            "scoringNameAbbr"   => "PA35",
        ],
        "125" => [
            "isReverseItem"     => false,
            "points"            => 127,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "46+ points allowed (PA46)",
            "scoringNameAbbr"   => "PA46",
        ],
        "127" => [
            "isReverseItem"     => false,
            "points"            => 128,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "prettyKey"         => "Yards allowed",
            "scoringName"       => "Yards Allowed (YA)",
            "scoringNameAbbr"   => "YA",
        ],
        "128" => [
            "isReverseItem"     => false,
            "points"            => 129,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "Less than 100 total yards allowed (YA100)",
            "scoringNameAbbr"   => "YA100",
        ],
        "129" => [
            "isReverseItem"     => false,
            "points"            => 130,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "100-199 total yards allowed (YA199)",
            "scoringNameAbbr"   => "YA199",
        ],
        "130" => [
            "isReverseItem"     => false,
            "points"            => 131,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "200-299 total yards allowed (YA299)",
            "scoringNameAbbr"   => "YA299",
        ],
        "131" => [
            "isReverseItem"     => false,
            "points"            => 132,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "300-349 total yards allowed (YA349)",
            "scoringNameAbbr"   => "YA349",
        ],
        "132" => [
            "isReverseItem"     => false,
            "points"            => 133,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "350-399 total yards allowed (YA399)",
            "scoringNameAbbr"   => "YA399",
        ],
        "133" => [
            "isReverseItem"     => false,
            "points"            => 134,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "400-449 total yards allowed (YA449)",
            "scoringNameAbbr"   => "YA449",
        ],
        "134" => [
            "isReverseItem"     => false,
            "points"            => 135,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "450-499 total yards allowed (YA499)",
            "scoringNameAbbr"   => "YA499",
        ],
        "135" => [
            "isReverseItem"     => false,
            "points"            => 136,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "500-549 total yards allowed (YA549)",
            "scoringNameAbbr"   => "YA549",
        ],
        "136" => [
            "isReverseItem"     => false,
            "points"            => 137,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "550+ total yards allowed (YA550)",
            "scoringNameAbbr"   => "YA550",
        ],
        "138" => [
            "isReverseItem"     => false,
            "points"            => 59,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Net Punts (PT)",
            "scoringNameAbbr"   => "PT",
        ],
        "139" => [
            "isReverseItem"     => false,
            "points"            => 60,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Punt Yards (PTY)",
            "scoringNameAbbr"   => "PTY",
        ],
        "140" => [
            "isReverseItem"     => false,
            "points"            => 61,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Punts Inside the 10 (PT10)",
            "scoringNameAbbr"   => "PT10",
        ],
        "141" => [
            "isReverseItem"     => false,
            "points"            => 62,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Punts Inside the 20 (PT20)",
            "scoringNameAbbr"   => "PT20",
        ],
        "142" => [
            "isReverseItem"     => false,
            "points"            => 63,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Blocked Punts (PTB)",
            "scoringNameAbbr"   => "PTB",
        ],
        "143" => [
            "isReverseItem"     => false,
            "points"            => 64,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Punts Returned (PTR)",
            "scoringNameAbbr"   => "PTR",
        ],
        "144" => [
            "isReverseItem"     => false,
            "points"            => 65,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Punt Return Yards (PTRY)",
            "scoringNameAbbr"   => "PTRY",
        ],
        "145" => [
            "isReverseItem"     => false,
            "points"            => 66,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Touchbacks (PTTB)",
            "scoringNameAbbr"   => "PTTB",
        ],
        "146" => [
            "isReverseItem"     => false,
            "points"            => 67,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Fair Catches (PTFC)",
            "scoringNameAbbr"   => "PTFC",
        ],
        "148" => [
            "isReverseItem"     => false,
            "points"            => 68,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Punt Average 44.0+ (PTA44)",
            "scoringNameAbbr"   => "PTA44",
        ],
        "149" => [
            "isReverseItem"     => false,
            "points"            => 69,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Punt Average 42.0-43.9 (PTA42)",
            "scoringNameAbbr"   => "PTA42",
        ],
        "150" => [
            "isReverseItem"     => false,
            "points"            => 70,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Punt Average 40.0-41.9 (PTA40)",
            "scoringNameAbbr"   => "PTA40",
        ],
        "151" => [
            "isReverseItem"     => false,
            "points"            => 71,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Punt Average 38.0-39.9 (PTA38)",
            "scoringNameAbbr"   => "PTA38",
        ],
        "152" => [
            "isReverseItem"     => false,
            "points"            => 72,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Punt Average 36.0-37.9 (PTA36)",
            "scoringNameAbbr"   => "PTA36",
        ],
        "153" => [
            "isReverseItem"     => false,
            "points"            => 73,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Punt Average 34.0-35.9 (PTA34)",
            "scoringNameAbbr"   => "PTA34",
        ],
        "154" => [
            "isReverseItem"     => false,
            "points"            => 74,
            "isTeamScoringItem" => false,
            "playerCategory"    => "punting",
            "scoringName"       => "Punt Average 33.9 or less (PTA33)",
            "scoringNameAbbr"   => "PTA33",
        ],
        "155" => [
            "isReverseItem"     => false,
            "points"            => 37,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "scoringName"       => "Team Win (TW)",
            "scoringNameAbbr"   => "TW",
        ],
        "155" => [
            "isReverseItem"     => false,
            "points"            => 86,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "Team Win (TW)",
            "scoringNameAbbr"   => "TW",
        ],
        "156" => [
            "isReverseItem"     => false,
            "points"            => 38,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "scoringName"       => "Team Loss (TL)",
            "scoringNameAbbr"   => "TL",
        ],
        "156" => [
            "isReverseItem"     => false,
            "points"            => 87,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "Team Loss (TL)",
            "scoringNameAbbr"   => "TL",
        ],
        "157" => [
            "isReverseItem"     => false,
            "points"            => 88,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "Team Tie (TIE)",
            "scoringNameAbbr"   => "TIE",
        ],
        "158" => [
            "isReverseItem"     => false,
            "points"            => 89,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "Points Scored (PTS)",
            "scoringNameAbbr"   => "PTS",
        ],
        "161" => [
            "isReverseItem"     => false,
            "points"            => 90,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "25+ point Win Margin (WM25)",
            "scoringNameAbbr"   => "WM25",
        ],
        "162" => [
            "isReverseItem"     => false,
            "points"            => 91,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "20-24 point Win Margin (WM20)",
            "scoringNameAbbr"   => "WM20",
        ],
        "163" => [
            "isReverseItem"     => false,
            "points"            => 92,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "15-19 point Win Margin (WM15)",
            "scoringNameAbbr"   => "WM15",
        ],
        "164" => [
            "isReverseItem"     => false,
            "points"            => 93,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "10-14 point Win Margin (WM10)",
            "scoringNameAbbr"   => "WM10",
        ],
        "165" => [
            "isReverseItem"     => false,
            "points"            => 94,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "5-9 point Win Margin (WM5)",
            "scoringNameAbbr"   => "WM5",
        ],
        "166" => [
            "isReverseItem"     => false,
            "points"            => 95,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "1-4 point Win Margin (WM1)",
            "scoringNameAbbr"   => "WM1",
        ],
        "167" => [
            "isReverseItem"     => false,
            "points"            => 96,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "1-4 point Loss Margin (LM1)",
            "scoringNameAbbr"   => "LM1",
        ],
        "168" => [
            "isReverseItem"     => false,
            "points"            => 97,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "5-9 point Loss Margin (LM5)",
            "scoringNameAbbr"   => "LM5",
        ],
        "169" => [
            "isReverseItem"     => false,
            "points"            => 98,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "10-14 point Loss Margin (LM10)",
            "scoringNameAbbr"   => "LM10",
        ],
        "170" => [
            "isReverseItem"     => false,
            "points"            => 99,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "15-19 point Loss Margin (LM15)",
            "scoringNameAbbr"   => "LM15",
        ],
        "171" => [
            "isReverseItem"     => false,
            "points"            => 100,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "20-24 point Loss Margin (LM20)",
            "scoringNameAbbr"   => "LM20",
        ],
        "172" => [
            "isReverseItem"     => false,
            "points"            => 101,
            "isTeamScoringItem" => true,
            "playerCategory"    => "coach",
            "scoringName"       => "25+ point Loss Margin (LM25)",
            "scoringNameAbbr"   => "LM25",
        ],
        "206" => [
            "isReverseItem"     => false,
            "points"            => 42,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "scoringName"       => "2pt Return (2PTRET)",
            "scoringNameAbbr"   => "2PTRET",
        ],
        "206" => [
            "isReverseItem"     => false,
            "points"            => 138,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "2pt Return (2PTRET)",
            "scoringNameAbbr"   => "2PTRET",
        ],
        "209" => [
            "isReverseItem"     => false,
            "points"            => 43,
            "isTeamScoringItem" => false,
            "playerCategory"    => "miscellaneous",
            "scoringName"       => "1pt Safety (1PSF)",
            "scoringNameAbbr"   => "1PSF",
        ],
        "209" => [
            "isReverseItem"     => false,
            "points"            => 139,
            "isTeamScoringItem" => true,
            "playerCategory"    => "DST",
            "scoringName"       => "1pt Safety (1PSF)",
            "scoringNameAbbr"   => "1PSF",
        ],
    ],
    'scoringItemsPPR'          => [
        "4"   => [
            "isReverseItem"     => false,
            "statId"            => 4,
            "points"            => 4,
            "isTeamScoringItem" => false,
        ],
        "8"   => [
            "isReverseItem"     => false,
            "statId"            => 8,
            "points"            => 1,
            "isTeamScoringItem" => false,
        ],
        "19"  => [
            "isReverseItem"     => false,
            "statId"            => 19,
            "points"            => 2,
            "isTeamScoringItem" => false,
        ],
        "20"  => [
            "isReverseItem"     => false,
            "statId"            => 20,
            "points"            => -2,
            "isTeamScoringItem" => false,
        ],
        "25"  => [
            "isReverseItem"     => false,
            "statId"            => 25,
            "points"            => 6,
            "isTeamScoringItem" => false,
        ],
        "26"  => [
            "isReverseItem"     => false,
            "statId"            => 26,
            "points"            => 2,
            "isTeamScoringItem" => false,
        ],
        "28"  => [
            "isReverseItem"     => false,
            "statId"            => 28,
            "points"            => 1,
            "isTeamScoringItem" => false,
        ],
        "43"  => [
            "isReverseItem"     => false,
            "statId"            => 43,
            "points"            => 6,
            "isTeamScoringItem" => false,
        ],
        "44"  => [
            "isReverseItem"     => false,
            "statId"            => 44,
            "points"            => 2,
            "isTeamScoringItem" => false,
        ],
        "48"  => [
            "isReverseItem"     => false,
            "statId"            => 48,
            "points"            => 1,
            "isTeamScoringItem" => false,
        ],
        "53"  => [
            "isReverseItem"     => false,
            "statId"            => 53,
            "points"            => 1,
            "isTeamScoringItem" => false,
        ],
        "63"  => [
            "isReverseItem"     => false,
            "statId"            => 63,
            "points"            => 6,
            "isTeamScoringItem" => false,
        ],
        "72"  => [
            "isReverseItem"     => false,
            "statId"            => 72,
            "points"            => -2,
            "isTeamScoringItem" => false,
        ],
        "74"  => [
            "isReverseItem"     => false,
            "statId"            => 74,
            "points"            => 5,
            "isTeamScoringItem" => false,
        ],
        "77"  => [
            "isReverseItem"     => false,
            "statId"            => 77,
            "points"            => 4,
            "isTeamScoringItem" => false,
        ],
        "80"  => [
            "isReverseItem"     => false,
            "statId"            => 80,
            "points"            => 3,
            "isTeamScoringItem" => false,
        ],
        "85"  => [
            "isReverseItem"     => false,
            "statId"            => 85,
            "points"            => -1,
            "isTeamScoringItem" => false,
        ],
        "86"  => [
            "isReverseItem"     => false,
            "statId"            => 86,
            "points"            => 1,
            "isTeamScoringItem" => false,
        ],
        "89"  => [
            "isReverseItem"     => false,
            "statId"            => 89,
            "points"            => 5,
            "isTeamScoringItem" => true,
        ],
        "90"  => [
            "isReverseItem"     => false,
            "statId"            => 90,
            "points"            => 4,
            "isTeamScoringItem" => true,
        ],
        "91"  => [
            "isReverseItem"     => false,
            "statId"            => 91,
            "points"            => 3,
            "isTeamScoringItem" => true,
        ],
        "92"  => [
            "isReverseItem"     => false,
            "statId"            => 92,
            "points"            => 1,
            "isTeamScoringItem" => true,
        ],
        "93"  => [
            "isReverseItem"     => false,
            "statId"            => 93,
            "points"            => 6,
            "isTeamScoringItem" => false,
        ],
        "93"  => [
            "isReverseItem"     => false,
            "statId"            => 93,
            "points"            => 6,
            "isTeamScoringItem" => true,
        ],
        "95"  => [
            "isReverseItem"     => false,
            "statId"            => 95,
            "points"            => 2,
            "isTeamScoringItem" => true,
        ],
        "96"  => [
            "isReverseItem"     => false,
            "statId"            => 96,
            "points"            => 2,
            "isTeamScoringItem" => true,
        ],
        "97"  => [
            "isReverseItem"     => false,
            "statId"            => 97,
            "points"            => 2,
            "isTeamScoringItem" => true,
        ],
        "98"  => [
            "isReverseItem"     => false,
            "statId"            => 98,
            "points"            => 2,
            "isTeamScoringItem" => true,
        ],
        "99"  => [
            "isReverseItem"     => false,
            "statId"            => 99,
            "points"            => 1,
            "isTeamScoringItem" => true,
        ],
        "101" => [
            "isReverseItem"     => false,
            "statId"            => 101,
            "points"            => 6,
            "isTeamScoringItem" => false,
        ],
        "101" => [
            "isReverseItem"     => false,
            "statId"            => 101,
            "points"            => 6,
            "isTeamScoringItem" => true,
        ],
        "102" => [
            "isReverseItem"     => false,
            "statId"            => 102,
            "points"            => 6,
            "isTeamScoringItem" => false,
        ],
        "102" => [
            "isReverseItem"     => false,
            "statId"            => 102,
            "points"            => 6,
            "isTeamScoringItem" => true,
        ],
        "103" => [
            "isReverseItem"     => false,
            "statId"            => 103,
            "points"            => 6,
            "isTeamScoringItem" => false,
        ],
        "103" => [
            "isReverseItem"     => false,
            "statId"            => 103,
            "points"            => 6,
            "isTeamScoringItem" => true,
        ],
        "104" => [
            "isReverseItem"     => false,
            "statId"            => 104,
            "points"            => 6,
            "isTeamScoringItem" => false,
        ],
        "104" => [
            "isReverseItem"     => false,
            "statId"            => 104,
            "points"            => 6,
            "isTeamScoringItem" => true,
        ],
        "123" => [
            "isReverseItem"     => false,
            "statId"            => 123,
            "points"            => -1,
            "isTeamScoringItem" => true,
        ],
        "124" => [
            "isReverseItem"     => false,
            "statId"            => 124,
            "points"            => -3,
            "isTeamScoringItem" => true,
        ],
        "125" => [
            "isReverseItem"     => false,
            "statId"            => 125,
            "points"            => -5,
            "isTeamScoringItem" => true,
        ],
        "128" => [
            "isReverseItem"     => false,
            "statId"            => 128,
            "points"            => 5,
            "isTeamScoringItem" => true,
        ],
        "129" => [
            "isReverseItem"     => false,
            "statId"            => 129,
            "points"            => 3,
            "isTeamScoringItem" => true,
        ],
        "130" => [
            "isReverseItem"     => false,
            "statId"            => 130,
            "points"            => 2,
            "isTeamScoringItem" => true,
        ],
        "132" => [
            "isReverseItem"     => false,
            "statId"            => 132,
            "points"            => -1,
            "isTeamScoringItem" => true,
        ],
        "133" => [
            "isReverseItem"     => false,
            "statId"            => 133,
            "points"            => -3,
            "isTeamScoringItem" => true,
        ],
        "134" => [
            "isReverseItem"     => false,
            "statId"            => 134,
            "points"            => -5,
            "isTeamScoringItem" => true,
        ],
        "135" => [
            "isReverseItem"     => false,
            "statId"            => 135,
            "points"            => -6,
            "isTeamScoringItem" => true,
        ],
        "136" => [
            "isReverseItem"     => false,
            "statId"            => 136,
            "points"            => -7,
            "isTeamScoringItem" => true,
        ],
        "206" => [
            "isReverseItem"     => false,
            "statId"            => 206,
            "points"            => 2,
            "isTeamScoringItem" => false,
        ],
        "206" => [
            "isReverseItem"     => false,
            "statId"            => 206,
            "points"            => 2,
            "isTeamScoringItem" => true,
        ],
        "209" => [
            "isReverseItem"     => false,
            "statId"            => 209,
            "points"            => 1,
            "isTeamScoringItem" => false,
        ],
        "209" => [
            "isReverseItem"     => false,
            "statId"            => 209,
            "points"            => 1,
            "isTeamScoringItem" => true,
        ],

    ],
];
